# Generated by Django 5.2.4 on 2025-07-27 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_hotelbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='booking_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_user', to='accounts.hoteluser'),
        ),
    ]
