# Generated by Django 5.2.4 on 2025-07-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hotelbooking_status_alter_hotelbooking_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='checkin_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='checkout_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
