# Generated by Django 5.2.4 on 2025-07-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_orders_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='checkin_time',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='checkout_time',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
