# Generated by Django 5.2.4 on 2025-07-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_hotelbooking_checkin_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelBooking',
        ),
    ]
