# Generated by Django 5.2.4 on 2025-07-28 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_hotelbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_start_date', models.DateField()),
                ('booking_end_date', models.DateField()),
                ('checkin_time', models.CharField(max_length=1000, null=True)),
                ('checkout_time', models.CharField(max_length=1000, null=True)),
                ('price', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('booking_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_user', to='accounts.hoteluser')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.hotel')),
            ],
        ),
    ]
