# Generated by Django 5.2.4 on 2025-07-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_hotelbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='booking_slug',
            field=models.SlugField(blank=True, max_length=1000, unique=True),
        ),
    ]
